/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  AtkObject *atko;
  GtkWidget *taula_principal;
  GtkWidget *llista;
  GtkWidget *reprodueix;
  GtkWidget *surt;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("Miniphono"));

  taula_principal = gtk_table_new (3, 3, TRUE);
  gtk_widget_show (taula_principal);
  gtk_container_add (GTK_CONTAINER (window1), taula_principal);

  llista = gtk_button_new_with_mnemonic (_("Selecciona una llista"));
  gtk_widget_show (llista);
  gtk_table_attach (GTK_TABLE (taula_principal), llista, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_widget_set_size_request (llista, 200, 50);

  reprodueix = gtk_button_new_with_mnemonic (_("reprodueix"));
  gtk_widget_show (reprodueix);
  gtk_table_attach (GTK_TABLE (taula_principal), reprodueix, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_widget_set_size_request (reprodueix, 100, 50);

  surt = gtk_button_new_with_mnemonic (_("surt"));
  gtk_widget_show (surt);
  gtk_table_attach (GTK_TABLE (taula_principal), surt, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_widget_set_size_request (surt, 100, 50);

  g_signal_connect ((gpointer) surt, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  atko = gtk_widget_get_accessible (window1);
  atk_object_set_name (atko, _("Miniphono"));


  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, taula_principal, "taula_principal");
  GLADE_HOOKUP_OBJECT (window1, llista, "llista");
  GLADE_HOOKUP_OBJECT (window1, reprodueix, "reprodueix");
  GLADE_HOOKUP_OBJECT (window1, surt, "surt");

  return window1;
}

